/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.world;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        for (int i = 0; i < 10; i++) {
            System.out.println("Iteration " + i);
            if (i % 2 == 0) {
                System.out.println("Even number");
            } else {   
                System.out.println("Odd number");
            }
            if (i == 5) {
                break;
            }
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
